---

apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController

metadata:
  name: agrrh-com-loadbalancers

spec:
  parentResource:
    apiVersion: agrrh.com/v1alpha1
    resource: loadbalancers
  hooks:
    sync:
      webhook:
        url: http://lbs-controller.metacontroller.svc/sync
    finalize:
      webhook:
        url: http://lbs-controller.metacontroller.svc/finalize
